x="hello world"
print(type(x))
x=10
print(type(x))
x=2.5
print(type(x))
x=1j
print(type(x))
x=["apple","banana","cherry"]
print(type(x))
x=("apple","banana","cherry")
print(type(x))
x=range(4)
print(type(x))
x={"name":"Dream","age":19}
print(type(x))
x={"apple","banana","cherry"}
print(type(x))
x=frozenset({"apple","banana","charry"})
print(type(x))
x=True
print(type(x))
x=b"hello"
print(type(x))
x=bytearray(5)
print(type(x))
x=memoryview(bytes(5))
print(type(x))
x=None
print(type(x))